language: python

python: 
    - "3.6"

install:
    - pip install -r requirements.txt
before_script:
  - psql -c 'create database -h localhost -p 5433 -U postgres fast-food-fast-db'
script:
    - pytest tests 
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
after_success:
    - coveralls