language: python

python: 
    - "3.6"

install:
    - pip install -r requirements.txt
before_script:
  - psql -c 'create database fast_food_fast_db;' -U postgres
  - psql -c 'create database test_fast_food_fast' -U postgres
  - python api/v2/init_db.py
script:
    - pytest tests 
services:
  - postgresql
after_success:
    - coveralls
notifications:
   email: false