language: python

python: 
    - "3.6"

install:
    - pip install -r requirements.txt
before_script:
  - psql -u postgres -h 127.0.0.1
  - psql -c 'create database fast-food-fast-db;' -U postgres
script:
    - pytest tests 
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
after_success:
    - coveralls