language: python

python: 
    - "3.6"

install:
 - pip install -r requirements.txt
before_script:
  - psql -c 'create database test_fast_food_fast;' -U postgres
  - psql -c '\l'
  - psql -c '\conninfo'
script:
    - pytest tests 
services:
  - postgresql
after_success:
    - coveralls
notifications:
   email: false