language: python

python: 
    - "3.6"

install:
    - pip install -r requirements.txt
before_script:
  - psql -c "CREATE DATABASE fast-food-fast-db;" -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD 'postgres';" -U postgres
script:
    - pytest tests 
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
after_success:
    - coveralls