language: python

python: 
    - "3.6"

install:
    - pip install -r requirements.txt
before_script:
  - psql -c 'create database fast-food-fast-db;' -U postgres
script:
    - pytest tests 
services:
  - postgresql
addons:
  postgresql: "10.0"
after_success:
    - coveralls