language: python
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt

script:
    - pytest tests --cov=api --cov-report term-missing

after_success:
    - coveralls
