language: python

python: 
    - "3.6"

install:
    - pip install -r requirements.txt
before_script:
  - psql -c 'create database fast_food_fast;' -U postgres
script:
    - pytest tests 
services:
  - postgresql
env:
  global:
  - PGPORT=5433
after_success:
    - coveralls