language: python

python: 
    - "3.6"

install:
 - pip install -r requirements.txt
before_script:
  - psql -U postgres < tests/v2/travis.sql
script:
    - pytest tests 
    - psql -c '\dt'
services:
  - postgresql
after_success:
    - coveralls
notifications:
   email: false